### ISSUE TITLE
how to search with job titles that have spaces in the title?

### ISSUE THREAD

**Issue by LlewAdamson-test** [PSavvateev/JobScrapingApp_Indeed.nl#1]
Hi there,

Just came across your repo - great stuff!

Been testing it - but came across an issue - how do you search for jobs that have spaces in them? Example; "Financial Controller"

All the best

**Comment by PSavvateev** [comment]
Please try to add "financial controller" into the variable positions in the parameters.py. If it is the only position, it should look like this: `positions=["Financial Controller"]`.

**Comment by PSavvateev** [comment]
just checked it - should work. Let me know, if you come across any issues

**Comment by LlewAdamson-test** [comment]
Weird - not working for me. A manual search is returning 4357 vacancies, but the dump only has 1376

Another question: how can I modify it to search in the USA? Is that possible?

**Comment by PSavvateev** [comment]
Did you apply any other changes in the code? I've discovered that classic US Indeed.com has  a bit different front, my app is specialized on a Dutch version only (www.nl.indeed.com). For American one, the scraper module should be changed dramatically.

**Comment by PSavvateev** [comment]
> Weird - not working for me. A manual search is returning 4357 vacancies, but the dump only has 1376
> 

Ok, I think I found the cause of the discrepancy: indeed.com automatically hides vacancies that are potentially duplicates, however, it  keeps showing the maximum found number. If you take number of pages * 15 (jobs per page) it will not be 4357. 
1367 is correct.

**Comment by PSavvateev** [comment]
> Another question: how can I modify it to search in the USA? Is that possible?
>
I will add search for US site in the next release
